/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLayoutRouteImport } from './routes/_app/layout'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppOrgSlugLayoutRouteImport } from './routes/_app/$orgSlug/layout'
import { Route as AppOrgSlugIndexRouteImport } from './routes/_app/$orgSlug/index'
import { Route as AppOrgSlugNotificationsRouteImport } from './routes/_app/$orgSlug/notifications'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgSlugLayoutRoute = AppOrgSlugLayoutRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOrgSlugIndexRoute = AppOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugNotificationsRoute = AppOrgSlugNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$orgSlug': typeof AppOrgSlugLayoutRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/$orgSlug/notifications': typeof AppOrgSlugNotificationsRoute
  '/$orgSlug/': typeof AppOrgSlugIndexRoute
}
export interface FileRoutesByTo {
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/$orgSlug/notifications': typeof AppOrgSlugNotificationsRoute
  '/$orgSlug': typeof AppOrgSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_app/$orgSlug': typeof AppOrgSlugLayoutRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/$orgSlug/notifications': typeof AppOrgSlugNotificationsRoute
  '/_app/$orgSlug/': typeof AppOrgSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$orgSlug'
    | '/auth/login'
    | '/'
    | '/$orgSlug/notifications'
    | '/$orgSlug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth/login' | '/' | '/$orgSlug/notifications' | '/$orgSlug'
  id:
    | '__root__'
    | '/_app'
    | '/_app/$orgSlug'
    | '/auth/login'
    | '/_app/'
    | '/_app/$orgSlug/notifications'
    | '/_app/$orgSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$orgSlug': {
      id: '/_app/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof AppOrgSlugLayoutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$orgSlug/': {
      id: '/_app/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof AppOrgSlugIndexRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    '/_app/$orgSlug/notifications': {
      id: '/_app/$orgSlug/notifications'
      path: '/notifications'
      fullPath: '/$orgSlug/notifications'
      preLoaderRoute: typeof AppOrgSlugNotificationsRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
  }
}

interface AppOrgSlugLayoutRouteChildren {
  AppOrgSlugNotificationsRoute: typeof AppOrgSlugNotificationsRoute
  AppOrgSlugIndexRoute: typeof AppOrgSlugIndexRoute
}

const AppOrgSlugLayoutRouteChildren: AppOrgSlugLayoutRouteChildren = {
  AppOrgSlugNotificationsRoute: AppOrgSlugNotificationsRoute,
  AppOrgSlugIndexRoute: AppOrgSlugIndexRoute,
}

const AppOrgSlugLayoutRouteWithChildren =
  AppOrgSlugLayoutRoute._addFileChildren(AppOrgSlugLayoutRouteChildren)

interface AppLayoutRouteChildren {
  AppOrgSlugLayoutRoute: typeof AppOrgSlugLayoutRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppOrgSlugLayoutRoute: AppOrgSlugLayoutRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
